### ISSUE TITLE
1.3.2-refactor.8 is not hot reloading

### ISSUE THREAD

**Issue by priezz** [gadicc/meteor-hmr#67] opened 2016-05-04 10:38 UTC
## The Problem

It seems that `hot` is not getting the signal, that the file content was changed on the disk, due to the broken websocket connection. I have added a simple check:
```
import { setHead, setRoutes } from "priezz_helpers"
import Home from "/client/imports/pages/Home"

setRoutes( {
    "/": { source: "/client/imports/pages/Home.jsx" },  /* I have to add '.jsx' extension explicitly */
} )

if( module.hot ) {
    console.log( "'hot' module available" )
    module.hot.accept( [ "/client/imports/pages/Home.jsx" ], () => console.log( "Home.jsx updated" ) )
}
```
_**Note:** `setRoute` routine is defined here [https://gitlab.com/priezz/meteor-helpers/blob/master/src/routes.jsx](https://gitlab.com/priezz/meteor-helpers/blob/master/src/routes.jsx). I use it adding `"priezz_helpers": "git+https://gitlab.com/priezz/meteor-helpers"` to dependencies in `package.json`._

I see, that `hot` module is loaded, however, when changing `Home.jsx` nothing happens until Meteor refreshes the page in a few seconds. The last thing I get in the console is:
```
[gadicc:hot] Connected and ready.
```
When launching Meteor with `HOT_PORT=3002 HOT_DEBUG=1 meteor run --settings settings-development.json` I get in the terminal:
```
[[[[[ .../meteor-react-hot ]]]]]

=> Started proxy.                             
   Determining active plugins                \
[gadicc:hot-build] (pGp): Starting new accelerator process
   Building the application                  /
[gadicc:hot-build] (pGp): Unhandled websocket err! { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
=> Starting gadicc:hot-build Accelerator (pGp) on port 3002.

=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
```

After the first pressing `Ctrl-C` I get the following in the terminal (full paths truncated):
```
~/.meteor/packages/meteor-tool/.1.3.2_4.gfnt1e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/ws/lib/WebSocket.js:181
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (~/.meteor/packages/meteor-tool/.1.3.2_4.gfnt1e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/ws/lib/WebSocket.js:181:16)
    at process.Package (packages/gadicc_hot-build/accelerator.js:106:1)
    at process.emit (events.js:117:20)
    at process.exit (node.js:750:17)
    at process.<anonymous> (.../meteor-react-hot/node_modules/jspm/lib/config/global-config.js:174:13)
    at process.g (events.js:180:16)
    at process.emit (events.js:117:20)
    at Signal.wrap.onsignal (node.js:800:46)
```

In my boilerplate `import "react-hot-loader/patch"` is in the first line of `/client/index.js`, which is the only JS file not in the `imports`. You can clone the full boilerplate from here [https://gitlab.com/priezz/meteor-react-hot.git](https://gitlab.com/priezz/meteor-react-hot.git).

## Environment

* Meteor version: 1.3.2.4
* ecmascript-hot version: 1.3.2-refactor.8
* Operating System: OS X 10.11.5 (15F31a)

**Comment by gadicc** [comment] 2016-05-04 11:05
Great, thanks for moving this to github!  I think the websocket error is actually safe to ignore since it only happens once and the accelerator still loads... I'll check to see why there's still an error and why the cleanup (on ctrl-c) is still throwing an error.

I googled and found that vim also does "safe" (atomic) writes.  I tried to look for C9 too but it was hard to google for too.  Before moving further, I'd love you to just try any other text editor (maybe whatever super simple one comes with OS X) to see if there's any difference (in which case, I have another strategy to try to fix this... thanks for confirming that the release from today doesn't fix this!).

Otherwise later today I'll take a look at the repo and see how things look my side.

**Comment by gadicc** [comment] 2016-05-04 11:20
Actually I had a sec to clone my side before heading out, I get:

```
Hot-reload initialized.
meteor-analytics.js:143Missing analyticsSettings in Meteor.settings.public
websocket.js:16[gadicc:hot] Connected and ready.
hot.js:73 [gadicc:hot] Updating ["/client/imports/pages/Home.jsx"]
routes.js:41 Home.jsx updated
```

BUT, I had to change

```diff
-    module.hot.accept( [ "/client/imports/pages/Home.jsx" ], () => console.log( "Home.jsx updated" ) )
+    module.hot.accept( [ "/client/imports/pages/Home" ], () => console.log( "Home.jsx updated" ) )
```
which shouldn't be necessary, and I'll look into that.

Meantime, please confirm with a different editor if this is indeed the problem on your side and not something else.

**Comment by priezz** [comment] 2016-05-04 11:22
TextEdit, Atom, Visual Studio Code - all the same.

2016-05-04 13:05 GMT+02:00 Gadi Cohen <notifications@github.com>:

**Comment by priezz** [comment] 2016-05-04 11:30
I can't reproduce you result. Getting rid of `.jsx` in `hot.accept` does
not lead me to `routes.js:41 Home.jsx update`. What OS and editor do you
use? I will try to run this under Linux...

2016-05-04 13:21 GMT+02:00 Alexandr PRIEZZHEV <a@priezz.net>:

**Comment by priezz** [comment] 2016-05-04 13:05
Exactly the same behavior (no reload both for `Home` nor `Home.jsx` and same errors) on `Ubuntu 16.04' with `gedit`, `vi`, and `nano` editors. On both, OS X and Linux I have Node 6.0 and NPM 3.7 and 3.8.6 installed (used for packages installation).

**Comment by gadicc** [comment] 2016-05-04 13:33
Hey wow, you've been busy!  Thanks for trying out all the editors and OSes!  I'll admit to being surprised to you still experiencing this over so many editors and platforms, especially since my clone of your repo worked here.  How are you running Linux?  If on a VM, are your files still stored in OSX and served over virtual network?

Either way, it still seems to be file change detection code that's causing a problem (which is still the root cause of the safe write issue), so I might try switching to something more reliable than stock node.  Atom have made their file watching code available so I might try that.

**Comment by gadicc** [comment] 2016-05-04 14:14
Can you give `gadicc:ecmascript-hot@=1.3.2-refactor.9` a spin too, just rushing this through before I head out again so hope it all works :>

**Comment by gadicc** [comment] 2016-05-04 14:15
I also added a big of extra debugging... for `HOT_DEBUG=2` you should see:

```
[gadicc:hot] Accelerator (dev): Got change event for /home/dragon/www/meteor-hmr/demo/client/colors.js
[gadicc:hot] Accelerator (dev): gadicc:ecmascript-hot/compile-ecmascript-hot.processFilesForTarget(client/colors.js)
[gadicc:hot] Accelerator (dev): hot.process(client/colors.js)
[gadicc:hot] Accelerator (dev): Creating a bundle for 1 changed file(s)...
```

**Comment by clayne11** [comment] 2016-05-04 16:39
`refactor.9` has fixed the issues I was having with `refactor.7` that was causing an HCP on every code change since it thought my entry point was being modified.

Working for me with:

OS: Mac OS X 10.11
Text editors: Atom, vim

Great work!

**Comment by gadicc** [comment] 2016-05-04 16:59
Awesome!  Thanks for reporting.  You can thank @priezz here who made me aware of that naming issue :D

Wait so, in `refactor.7` vim didn't work (and atom?), and in `refactor.9` it does?  That's great news!  I'll be so happy to put this issue to rest.  Just note, refactor.9 was kind of rushed, I still need to more gracefully handle delete/rename events, but at least we have it picking up the changes!  You can also thank the Atom guys for releasing their alternative path watching code for node.

**Comment by clayne11** [comment] 2016-05-04 17:01
I think Atom was actually working fine before - the Atom issue I was having was related to https://github.com/gadicc/meteor-hmr/issues/65. Vim definitely did not work before though, and now it is, so for me at least on OS X you have solved the issue of atomic writes.

**Comment by gadicc** [comment] 2016-05-04 17:04
Yay!  Finally  :tada:

**Comment by priezz** [comment] 2016-05-04 18:02
Linux is running on bare metal... This is default Ubuntu LTS setup, w/o any
tweaks.
I have to mention that previous version of ecmascript-hot (1.3.1_1) worked
perfect, webpack works fine as well.

2016-05-04 15:33 GMT+02:00 Gadi Cohen <notifications@github.com>:

**Comment by priezz** [comment] 2016-05-04 18:37
Still bad news from me :( Sorry for that. After updating to refactor.9 I have tried Atom, C9, vi (not vim) and nano in OS X - does not work. And I see no additional debugging info (`HOT_PORT=3002 HOT_DEBUG=2 meteor run --settings settings-development.json`), that looks very strange. The same picture in Ubuntu.

P.S. I have updated the boilerplate repo with the changes we discussed.

**Comment by gadicc** [comment] 2016-05-05 07:51
Thanks, @priezz.  It's ok... I'd like to get this working :)

Yeah, 1.3.1_1 did everything via Meteor, which was a lot less work for us but limited the project quite severely.  Our new way is faster, more flexible and more sustainable; we just have to work out these initial issues once off.

One other thing that occurred to me, I don't think it's your issue, but did you restart Meteor after upgrading the package?  Currently if you don't do that, it will still use the old version of the accelerator, tracking in #69.

With your latest master, it all works out the box for me :/   client:

```
Hot-reload initialized.
Missing analyticsSettings in Meteor.settings.public
[gadicc:hot] Connected and ready.
[gadicc:hot] Updating ["/client/imports/pages/Home.jsx"]
Home.jsx updated
[gadicc:hot] Skipping HCP after successful HMR
```

<details>
<summary>`$ HOT_DEBUG=2 meteor -p 4500`</summary>
```
[[[[[ ~/www/repro/priezz-meteor-react-hot ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
   Loading plugin `compile-ecmascript-ho...  /
[gadicc:hot-build] (XY9): Starting new accelerator process
=> Starting gadicc:hot-build Accelerator (XY9) on port 4502.

   Building the application                  \
[gadicc:hot-build] (XY9): Connected to new accelerator

[gadicc:hot] Accelerator (XY9): Connection from hot-build (XY9)
   Building the application                  \
[gadicc:hot] Accelerator (XY9): Loading plugin "gadicc:ecmascript-hot/compile-ecmascript-hot" (5c4) from /home/dragon/.meteor/packages/gadicc_ecmascript-hot/1.3.2-refactor.9/plugin.compile-ecmascript-hot.os
   Building the application                  -
[gadicc:hot] Accelerator (XY9): Loading plugin "gadicc:ecmascript-hot/compile-ecmascript-hot" (5c4) from /home/dragon/.meteor/packages/gadicc_ecmascript-hot/1.3.2-refactor.9/plugin.compile-ecmascript-hot.os
=> Started your app.                          
                                              
=> App running at: http://localhost:4500/     
                                              
[gadicc:hot] Accelerator (XY9): Got change event for /home/dragon/www/repro/priezz-meteor-react-hot/client/imports/pages/Home.jsx

[gadicc:hot] Accelerator (XY9): gadicc:ecmascript-hot/compile-ecmascript-hot.processFilesForTarget(client/imports/pages/Home.jsx)

[gadicc:hot] Accelerator (XY9): hot.process(client/imports/pages/Home.jsx)

[gadicc:hot] Accelerator (XY9): Creating a bundle for 1 changed file(s)...
```
</details>

Not sure if the difference between that and what you're getting leads to any more clues.  Still sounds like the file watching is failing.  Good to know that Webpack works too, I can always look into that code... but the main thing is that we should work where Meteor works, and we're now using the same patchwatcher module as Meteor, minus a fallback which triggers after up to 5s to double check.  How quickly does Meteor notice your code has changed?  Although it doesn't sound like you have any particular special setup and most of our users are running on OSX without problems.

Thanks for your help in trying to resolve this... let me know if you think of anything else and I'll do the same.  I can also try add some more debugging stuff to show the exact paths we're watching.

**Comment by priezz** [comment] 2016-05-05 10:00
Yes, I always restart meteor after the update.

I can't explain that... I have even tried to delete the project folder (both on OS X and Linux), clone from git, run `npm install` (not `meteor npm install`!), then `HOT_DEBUG=2 meteor -p 4500` (to completely follow your settings) - on both OSs I get websocket error, which you don't:
```
=> Started proxy.
   Determining active plugins                \
[gadicc:hot-build] (zEW): Starting new accelerator process
   Building the application                  \
[gadicc:hot-build] (zEW): Unhandled websocket err! { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
=> Starting gadicc:hot-build Accelerator (zEW) on port 4502.

=> Started your app.

=> App running at: http://localhost:4500/
```
I have no extra debugging messages, that is not a good sign.

Starting output in the browser console:
```
Hot-reload initialized.                                     modules.js:27624:9
[gadicc:hot] Connected and ready.                gadicc_hot.js:347:3
```
After that I change `Some text here` in the `/client/imports/pages/Home.jsx` to `Some text HERE` and in about **10 seconds** (yes, that long!) Meteor starts page refresh and I get in the console:
```
[gadicc:hot] Disconnected, attempting to reconnect...            gadicc_hot.js:364:5
```
The only new message, which appears in the terminal, is `=> Client modified -- refreshing`.

@gadicc, I have written you an email with my skype id, maybe it will be more productive to communicate with you there to find the reason.

**Comment by gadicc** [comment] 2016-05-05 11:11
@priezz, thanks for all the info, as usual.  I think you're right about the websocket issue, I'm sorry for not thinking about the full implications of this a bit earlier on.  Can you try `refactor.10` and see if it makes any difference?  We wait a bit longer before trying and keep trying to reconnect if we fail.  If this solves your issue, it might be time to upgrade your PC :D

Thanks, got your email... I'm heading out now but try the above and let's see if it makes any difference.  I'll be back a bit later.  Although tbh, I'm not really sure what I can do over skype....  maybe teamviewer? :)  But hopefully this will fix it!  Because I don't have any other ideas atm.

**Comment by priezz** [comment] 2016-05-05 12:01
It does not help.
```=> Started proxy.                             
   Determining active plugins                \
[gadicc:hot-build] (eSR): Starting new accelerator process
   Building the application                  |
[gadicc:hot-build] (eSR): Still can't reach accelerator after 1s, will keep retrying...
=> Starting gadicc:hot-build Accelerator (eSR) on port 22026.

=> Started your app.                          
                                              
=> App running at: http://localhost:21026/    

```

**Comment by gadicc** [comment] 2016-05-05 15:06
Sorry, I'm useless... I rushed to publish the above before I left, and left out the actual line to try reconnect!  Can you try `refactor.11`?

**Comment by clayne11** [comment] 2016-05-05 16:23
`refactor.11` is not hot reloading at all for me. I'm not getting any `log` statements in the console and it's simply doing a full HCP every time I make a code change.

**Comment by gadicc** [comment] 2016-05-05 16:31
Ah no ways :(  Hope I didn't break the atomic write support... I started ignoring "delete" events but usually the "delete" and "changed" events always came together.  Can you try with `HOT_DEBUG=3` and see what events are coming?  (The debug log shows the event before we ignore it).  Heading out again now though.  Damn, thought we had this licked finally.

**Comment by gadicc** [comment] 2016-05-05 16:31
@clayne11 thanks for checking every single release, btw!

**Comment by clayne11** [comment] 2016-05-05 16:32
I'm using Atom which I don't believe does atomic writes because it was working for me before you fixed the atomic write support.

**Comment by gadicc** [comment] 2016-05-05 16:35
oops, I think it's [this line](https://github.com/gadicc/meteor-hmr/commit/84ced54d1d8a733cad5208d12f29085cee537b68#diff-cee0737c9fde27361798f779caef3625R64.  It *was* meant to be set to `false`.  Will fix when I'm back home, or see if I can push out a quick update before my lift arrives.

**Comment by clayne11** [comment] 2016-05-05 16:36
`HOT_DEBUG=3` doesn't add anything to the console.

**Comment by gadicc** [comment] 2016-05-05 16:38
1.3.2-refactor.12 busy publishing, gotta run.

**Comment by priezz** [comment] 2016-05-05 17:00
Triple HOORAY! It finally works! :) Please investigate, why it does not work with `.jsx` extension specified explicitly. Should I open new issue for that?

**Comment by gadicc** [comment] 2016-05-06 06:29
Yay!  Finally haha.  Thanks for hanging in there and helping us fix this.

@clayne11, I meant the server logs, but either way, I had inadvertently (in `.11`) stopped sending anything to the accelerator, so, fail :D  Thanks for checking this out for us though!

**Comment by priezz** [comment] 2016-05-06 11:24
I believe, the issue could be closed. @gadicc, thank you again for your efforts!

I have updated the boilerplate https://gitlab.com/priezz/meteor-react-hot.git and the module behind it to provide automatic hot-reload for the routes (FlowRouter based). README is added as well. Now it is easy as:
```
setRoutes( {
    "/": { source: "/client/imports/pages/Home.jsx" },
}, module.hot )
```

**Comment by gadicc** [comment] 2016-05-06 14:00
Great stuff!  Thanks again for sticking in there and helping us solve this.  As mentioned on the forums, I added your boilerplate to the new [Boilerplates docs](https://github.com/gadicc/meteor-hmr/blob/master/docs/Boilerplates.md), thanks for this.

**Closed by gadicc** 2016-05-06 14:00 UTC
