### ISSUE TITLE
"No (relevant) hot.accept() in..." (with an incomplete import chain)

### ISSUE THREAD

**Issue by smeijer** [gadicc/meteor-hmr#126] opened 2016-07-29 14:51 UTC
## Description of Problem

Whatever I do or change, I always get the error: `No (relevant) hot.accept() in`.
```
[gadicc:hot] Updating ["/src/client/modules/profiles/components/list.js"]
[gadicc:hot] No (relevant) hot.accept() in 
  /src/client/modules/profiles/components/list.js > 
  /src/client/modules/profiles/containers/list.js. Need to reload.

[gadicc:hot] HMR failed, allowing HCP... 
```

## Environment

* **Meteor version**: Meteor 1.3.5.1
* **ecmascript-hot version**: gadicc:ecmascript-hot  2.0.0-beta.6
* **Operating System**: Windows 10, Home x64

## Supporting files

<details>
<summary>`.babelrc` </summary>
```js
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    "transform-decorators-legacy",
    "react-hot-loader/babel"
  ]
}
```
</details>

## Project Code

<details>
<summary>`/src/modules/core/components/error_reporter.js` </summary>
```js
import React, { PropTypes } from 'react';
import Redbox from 'redbox-react';

const ErrorReporter = ({ error }) => {
  /* eslint no-console: ["error", { allow: ["error"] }] */
  console.error(error);
  return <Redbox error={error} />;
};

ErrorReporter.propTypes = {
  error: PropTypes.instanceOf(Error).isRequired,
};

export default ErrorReporter;
```
</details>

<details>
<summary>`/src/modules/core/containers/main_layout.js` </summary>
```js
// Simplified version, normally I would import a component
import React from 'react';
export default ({ content }) => (
  <div>{content()}</div>
);
```
</details>

<details>
<summary>`/src/modules/profiles/components/list.js` </summary>
```js
import React from 'react';
export default () => (
  <div>Hello World!</div>
);
```
</details>

<details>
<summary>`/src/modules/profiles/containers/list.js` </summary>
```js
// Simplified version, normally there is some data injection here
import Component from '../components/list';
export default Component;
```
</details>

<details>
<summary>`/src/modules/profiles/routes.js` </summary>
```js
import ErrorReporter from '../core/components/error_reporter';

const CONTAINERS = {
  MAIN_LAYOUT: '../core/containers/main_layout',
  PROFILE_LIST: './containers/list',
};

// So we can call Router again later during hot reload
var localRouter;

export default function (injectDeps, { Router }) {
  localRouter = Router;
  
  const layout = (props) => {
    const Layout = require(CONTAINERS.MAIN_LAYOUT).default;
    const MainLayout = injectDeps(Layout);

    return (
      <AppContainer errorReporter={ErrorReporter}>
        <MainLayout {...props} />
      </AppContainer>
    );
  };

  Router.route('/profiles', {
    name: 'profiles.list',
    action() {
      const ProfileList = require(CONTAINERS.PROFILE_LIST).default;
      mount(layout, {
        content: () => (<ProfileList />),
      });
    },
  });
}

if (module.hot) {
  const files = Object.values(CONTAINERS);
  module.hot.accept(files, function () {
    localRouter._current.route._action(localRouter._current.params);
  });
}
```
</details>

**Comment by smeijer** [comment] 2016-07-29 15:01
I have no idea if this is relevant, but can it be that there is an issue in path resolving? As the server side console is reporting files to be watched with full path's, the client is talking in relative from project root, while we are `accepting` relative from the current file? (`routes.js`)

<details>
<summary>server console output</summary>
```shell
# removed unrelated files, but dit not change order
[gadicc:hot] Accelerator (xb5): Got fileData from
     gadicc:ecmascript-hot/compile-ecmascript-hot (y6N), watching: 
c:\dev\try-ecmascript-hot\src\client\lib\_reactHotLoader.js,
c:\dev\try-ecmascript-hot\src\client\modules\core\components\main_layout.js,
c:\dev\try-ecmascript-hot\src\client\modules\core\containers\main_layout.js, 
c:\dev\try-ecmascript-hot\src\client\modules\profiles\actions\index.js,
c:\dev\try-ecmascript-hot\src\client\modules\profiles\actions\profiles.js,
c:\dev\try-ecmascript-hot\src\client\modules\profiles\components\list.js,
c:\dev\try-ecmascript-hot\src\client\modules\profiles\containers\list.js,
c:\dev\try-ecmascript-hot\src\client\modules\profiles\locales\index.js,
c:\dev\try-ecmascript-hot\src\client\modules\profiles\reducers\index.js,
c:\dev\try-ecmascript-hot\src\client\modules\profiles\reducers\list.js,
c:\dev\try-ecmascript-hot\src\client\modules\profiles\index.js,
c:\dev\try-ecmascript-hot\src\client\modules\profiles\routes.js,  
c:\dev\try-ecmascript-hot\src\client\configs\context.js,
c:\dev\try-ecmascript-hot\src\client\configs\redux.js, 
c:\dev\try-ecmascript-hot\src\meteor.startup.js,
c:\dev\try-ecmascript-hot\src\client\main.js
```
</details>

**Comment by gadicc** [comment] 2016-07-29 18:06
Yes, you're right.  Unless I missed something, this looks like a bug.  Can you try pass `module.hot.accept` a file at a time (vs the array), and also maybe with the `.js` at the end?  Just some things that come to mind that could be broken here.  Surprising though, it all looks good.

Don't worry, the watch paths on the server don't affect anything on the client.  On the client, relative paths should correctly resolve to complete module ids.  If you're really interested, you could take a look at the `hot` global and see how we store everything, maybe it will make more sense :>  (On that note, if your app is cloneable, or available online, I could take a look).

Once this is working though, I feel like you actually need to use the updated modules in your accept function, but do vaguely recall that with mantra we did something hacky like this and it still worked, but I think that was with the old version of react-hot-loader?  Anyways, one thing at a time :>

**Comment by smeijer** [comment] 2016-07-29 18:35
I've tried a few different ways of `accepting`, but none of them worked:

```js
if (module.hot) {
  const files = [
    './containers/list',
    './containers/list.js',
    '/src/client/modules/profiles/containers/list',
    '/src/client/modules/profiles/containers/list.js',
  ]

  // tried 4 times while incrementing this 0,
  module.hot.accept(files[0], function () {
    localRouter._current.route._action(localRouter._current.params);
  });
}
```

If I look at the console to what modules are loaded, I see the following result:

```js
Object.keys(hot.allModules).filter(x => 
  x.indexOf('/profiles/') > -1
)

// left some files out to keep it clear
[
  "/src/client/modules/profiles/components",
  "/src/client/modules/profiles/components/list.js",
  "/src/client/modules/profiles/containers",
  "/src/client/modules/profiles/containers/list.js",
  "/src/client/modules/profiles/index.js",
  "/src/client/modules/profiles/routes.js"
]
```

I'm not sure if this means anything, but the files I'm `accepting` are in the `allModules` object. I guess that's where you determine if it's okay to hot load it?

Unfortunately this repo is not clone-able. If really necessary I can take a look if I can minimize it to a reproduction.

**Comment by smeijer** [comment] 2016-07-29 23:00
@gadicc, to make things easier; I've stripped down my app till the last reproducible bit. You'll find it in the repo linked below. The `containers` are nothing more than pipe-troughs. Import and export from the `Components`. I did this purely to leave the structure of my app intact.

There is a `start.bat` file that I use to startup my meteor app's so they are connected to a local database. I have the same issue when I just run `meteor` from the command line. So that is something you can ignore.

https://github.com/smeijer/meteor-hmr-issue-126

**Comment by smeijer** [comment] 2016-07-30 11:50
Moving the `src/client/modules` folder to `imports/modules` makes the thing work. According to the documentation it should work as well without using the `imports` folder, given the 'hack' provided above by going trough `FlowRouter`.

I guess this is not the case? Is this something you want to support, or should we just put all the stuff in the `imports` dir?

I wish meteor had an `--no-auto-resolve` or `--strict-import` switch.

**Comment by gadicc** [comment] 2016-07-30 15:50
Hey, first off, thanks for the minimalist reproduction!  Super helpful to be able to look at the running site.

Next off, an apology; I should have clicked a lot sooner on this one.  meteor-hmr relies on meteor's import scanner, that is, for Meteor to work out which files import which files.  You can verify this by viewing-source, loading up the `app.js`, and searching for `routes.js` module signature:

```js
}],"routes.js":["react","react-mounter","react-hot-loader","../core/components/error_reporter",function(require,exports,module){
```

The array elements up until the module are the dependencies; as you can see, according to Meteor, routes.js does not import `src/client/modules/profiles/routes.js`.

This is because for the static analysis to work, dynamic module names are not possible.  What's always guaranteed to work is a pure text string, although some import scanners can handle simple concatenation and constant resolution - I'm not sure of the exact specifics of Meteor/reify though.

Anyway, I confirmed that using strings instead of constants in the require lines does indeed work as expected, i.e.

```diff
-     const Layout = require(CONTAINERS.MAIN_LAYOUT).default;
+     const Layout = require('../core/containers/main_layout').default;

-       const ProfileList = require(CONTAINERS.PROFILE_LIST).default;
+       const ProfileList = require('./containers/list').default;
```

Since `module.hot.accept()` happens in the browser runtime, it doesn't have this requirement.

If you're saying that everything worked in `imports` even with constants, I guess there are some special rules about the imports vs non-imports dirs in Meteor's import scanner.

Once again, thanks for the reproduction and the time you spent working on this yourself!

**Comment by gadicc** [comment] 2016-07-30 15:52
Marking as `invalid` just because this is out of our control and isn't an issue with the meteor-hmr code.

**Comment by gadicc** [comment] 2016-07-30 15:54
Mmm, OTOH, I do wonder if we could keep track of `require()` calls in the client runtime to augment the dependency chain we get from Meteor.  It's not something I'd have any time to work on for quite some time though :/

**Comment by smeijer** [comment] 2016-07-30 23:40
Just to make this complete, so there are no misunderstandings. 

> If you're saying that everything worked in imports even with constants,

Well.. Not totally. At first the files weren't included  in the build at all. Meteor simply did not detect them as being required.

Then I only added an import statement at the top. And left the rest unchanged. From that moment it worked. So yes, the `require` is by using a constant. But the file has been `import`ed at the top of the file.

**Comment by gadicc** [comment] 2016-07-31 06:51
Oh yeah, sure... as long as there's at least one explicit import somewhere, it will work (you could likewise add the import line to your files outside of the `imports` directory).

**Closed** 2016-08-01 08:40 UTC
Labels: invalid
