### ISSUE TITLE
possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by lyquocnam** [gadicc/meteor-hmr#34] opened 2016-04-10 19:20 UTC
```
Client modified -- refreshing (x7)(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (C:\tools\fs\files.js:1486:10)
    at Object.watch (C:\tools\fs\safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (C:\tools\fs\watch.js:469:35)
    at C:\tools\fs\watch.js:547:18
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.3.2-rc.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at onWatchEvent (C:\tools\fs\watch.js:536:11)
    at thenCallback (C:\tools\utils\func-utils.js:37:18)
    at C:\Users\lyquo\AppData\Local\.meteor\packages\cosmos_browserify\0.8.4\plugin.CosmosBrowserify.os\npm\node_modules\meteor\promise\promise\node_modules\meteor-promise\fiber_pool.js:33:40
=> Client modified -- refreshing (x16)
```

**Comment by gadicc** [comment] 2016-04-11 08:27
How often are you seeing this?

From the stack trace, this is coming from Meteor's file listening code, which we don't use.

If you're seeing this often, can you check if it goes away if you switch back to the real `ecmascript` package, in case I'm missing something?

**Comment by lyquocnam** [comment] 2016-04-11 08:50
about 0.5 -> 1 hours
last day, it has 3 times

**Comment by gadicc** [comment] 2016-04-12 07:35
Ok great, if it's happening that often can you switch back to the real `ecmascript` and see if the problem goes away?  I'd just like to confirm that this really is caused by this package.

**Comment by lyquocnam** [comment] 2016-04-12 07:57
**real ecmascript** does not problems @gadicc i used it before swich to **emascript-hot**

**Comment by gadicc** [comment] 2016-04-12 08:07
ok great, thanks.  am looking into this.

**Comment by clayne11** [comment] 2016-04-27 15:19
I hit this yesterday. First time I've ever seen it. Definitely a bug, but seems pretty inconsequential and intermittent.

**Comment by gadicc** [comment] 2016-04-28 08:19
Thanks for reporting that it's still present in the latest versions.  Yeah, nothing won't work because of this, but would like to hunt it down before final release.

**Comment by anberger** [comment] 2016-05-02 09:37
I get the same error! It just appears occasional... I use React 15.0.0.2 + Meteor 1.3.2.4 

`(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1175:8)
    at Object.files.watchFile (/tools/fs/files.js:1486:10)
    at Object.watch (/tools/fs/safe-pathwatcher.js:85:9)
    at Watcher._watchFileOrDirectory (/tools/fs/watch.js:469:35)
    at /tools/fs/watch.js:547:18
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/andreasberger/.meteor/packages/meteor-tool/.1.3.2_4.a7ko6p++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at onWatchEvent (/tools/fs/watch.js:536:11)
    at thenCallback (/tools/utils/func-utils.js:37:18)
    at /Users/andreasberger/.meteor/packages/coffeescript/.1.0.17.oki7z9++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:33:40`

**Comment by gadicc** [comment] 2016-05-04 09:52
Hey all, I've looked at this quite thoroughly and my conclusions are as follows:

1) The error above is from Meteor's file watching code, not ours.
2) Because this doesn't happen with regular ecmascript, perhaps we're affecting it somehow.
3) The only file watching code outside of the accelerator is for your `.babelrc` files (up to 3).
4) I can only guess that either a) we're reaching the limit earlier because of the extra files or b) there's some kind of conflict because Meteor is already watching the directories these files are in.

In any event, it's a warning, not an error, and I don't think there's a problem here.  But either way, hopefully next Meteor (1.3.3) will include official babelrc support, and this won't be our responsibility anymore :)  Nevertheless, leaving this open for now.

**Comment by clayne11** [comment] 2016-05-04 16:43
I think we should remove the watchers on `.babelrc`. I don't think they add much value and they're clearly causing quite a few issues.

**Comment by gadicc** [comment] 2016-05-04 17:01
Yeah, that's a very possible solution here (or I guess I can also try atom's patchwatcher module now that we know that that works).  So let's leave this open and I'll try one of those before the next release.

**Comment by gadicc** [comment] 2016-05-05 11:15
Since it's our prime suspect, in `refactor.10`, I use a release of `babel-compiler-babelrc` which doesn't watch your .babelrc files, so let's see if it helps.

**Comment by Vincent-P** [comment] 2016-05-08 09:06
I stil have this issue when it's not #73, both happens very frequently.

**Comment by JeremySaks** [comment] 2016-05-11 16:04
For what it's worth, I get this warning from time to time since Meteor 1.3.2.x and I do **not** have any hmr functionality or `ecmascript-hot` installed. So it's not deriving from this project.

**Comment by genyded** [comment] 2016-05-12 06:15
Same here... seeing this with and without HMR - so I don't think it's HMR specific.

**Comment by gadicc** [comment] 2016-05-12 07:47
thanks @JeremySaks and @genyded!  That's super helpful.  I've been struggling to see how meteor-hmr could affect this but reports until now had been that the problem didn't exist without it.

I'm closing this issue, which looks like it's already being tracked in https://github.com/meteor/meteor/issues/6247, but I'm happy to re-open if any new evidence shows that meteor-hmr has any impact.

**Closed by gadicc** 2016-05-12 07:47 UTC
Labels: invalid
